server:
  port: 8091

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 150MB
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/twitterdownloader
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: 'spring:session'
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

cors:
  origins: http://localhost:3000